name: Push docker image

on:
    push:
        branches: [main]

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Login to Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.digitalocean.com
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: registry.digitalocean.com/tselementes/loaner:options
